llms:
  openai:
    chat_model: "gpt-4o"
    embedding_model: "text-embedding-ada-002"

embeddings:
  vectordb_path: "data/vectordb"

similarity_search:
  top_k: 10
  # cohere_reranker: "rerank-english-v3.0"

data:
  path: "data"
  movie: "data/Movie"
  final_data: "data/Movie/final_data.jsonl"
  conversations: "data/Movie/Conversation.txt"
  user_map: "data/Movie/user_ids.json"
  item_map: "data/Movie/item_map.json"  
  session_db: "data/chat_sessions.db"

api:
  base_url: http://127.0.0.1:8050
  port: 8050
